
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME_LOCAL"] %>
  password: <%= ENV["DATABASE_PASSWORD_LOCAL"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>

development:
  <<: *default
  database: to_do_insales_development

test:
  <<: *default
  database: to_do_insales_test

production:
  <<: *default
  database: <%= ENV["DATABASE"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
